/*
    MIT License

    Copyright (c) 2017 Leo Lindhorst

    Permission is hereby granted, free of charge, to any person obtaining a copy
    of this software and associated documentation files (the "Software"), to deal
    in the Software without restriction, including without limitation the rights
    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
    copies of the Software, and to permit persons to whom the Software is
    furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in all
    copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    SOFTWARE.
*/

/* Header file generated by fdesign on Sat Feb 25 18:19:48 2017 */

#ifndef FD_libformsGUI_h_
#define FD_libformsGUI_h_

#include <forms.h>
#include "list/list.h"

#if defined __cplusplus
extern "C"
{
#endif

/* Callbacks, globals and object handlers */

void insertRecordCallback( FL_OBJECT *, long );
void searchRecordsCallback( FL_OBJECT *, long );
void deleteRecordCallback( FL_OBJECT *, long );
void sortRecordsCallback( FL_OBJECT *, long );


/* Forms and Objects */

typedef struct {
    FL_FORM   * libformsGUI;
    void      * vdata;
    char      * cdata;
    long        ldata;
    FL_OBJECT * trigger_object;
    FL_OBJECT * insert_view;
    FL_OBJECT * insert_input_title;
    FL_OBJECT * insert_input_artist;
    FL_OBJECT * insert_input_borrower;
    FL_OBJECT * insert_button;
    FL_OBJECT * show_view;
    FL_OBJECT * search_input_title;
    FL_OBJECT * search_input_artist;
    FL_OBJECT * search_input_borrower;
    FL_OBJECT * search_button;
    FL_OBJECT * table_view_container;
    FL_FORM   * table_view;
} FD_libformsGUI;

FD_libformsGUI * create_form_libformsGUI( void );

void setTableView(tList* source, FD_libformsGUI* gui);

#if defined __cplusplus
}
#endif

#endif /* FD_libformsGUI_h_ */
