/* Header file generated by fdesign on Sat Feb 25 18:19:48 2017 */

#ifndef FD_libformsGUI_h_
#define FD_libformsGUI_h_

#include <forms.h>
#include "list/list.h"

#if defined __cplusplus
extern "C"
{
#endif

/* Callbacks, globals and object handlers */

void insertRecordCallback( FL_OBJECT *, long );
void searchRecordsCallback( FL_OBJECT *, long );
void deleteRecordCallback( FL_OBJECT *, long );


/* Forms and Objects */

typedef struct {
    FL_FORM   * libformsGUI;
    void      * vdata;
    char      * cdata;
    long        ldata;
    FL_OBJECT * trigger_object;
    FL_OBJECT * insert_view;
    FL_OBJECT * insert_input_title;
    FL_OBJECT * insert_input_artist;
    FL_OBJECT * insert_input_borrower;
    FL_OBJECT * insert_button;
    FL_OBJECT * show_view;
    FL_OBJECT * search_input_title;
    FL_OBJECT * search_input_artist;
    FL_OBJECT * search_input_borrower;
    FL_OBJECT * search_button;
    FL_OBJECT * table_view_container;
    FL_FORM   * table_view;
} FD_libformsGUI;

FD_libformsGUI * create_form_libformsGUI( void );

void setTableView(tList* source, FD_libformsGUI* gui);

#if defined __cplusplus
}
#endif

#endif /* FD_libformsGUI_h_ */
