/* Form definition file generated by fdesign on Sat Feb 25 18:19:48 2017 */

#include <stdlib.h>
#include "gui.h"
#include "libforms.h"


/***************************************
 ***************************************/

FD_libformsGUI *
create_form_libformsGUI( void )
{
    FL_OBJECT *obj;
    FD_libformsGUI *fdui = ( FD_libformsGUI * ) fl_malloc( sizeof *fdui );

    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->libformsGUI = fl_bgn_form( FL_NO_BOX, 1276, 1386 );

    fdui->trigger_object = fl_bgn_group();
    fl_end_group( );

    obj = fl_add_box( FL_FLAT_BOX, 0, 0, 1276, 1386, "" );

    obj = fl_add_text( FL_NORMAL_TEXT, 70, 40, 470, 60, "Media Manager" );
    fl_set_object_lsize( obj, FL_HUGE_SIZE );

    fdui->insert_view = fl_bgn_group( );

    obj = fl_add_text( FL_NORMAL_TEXT, 70, 140, 230, 30, "Insert" );
    fl_set_object_lsize( obj, FL_LARGE_SIZE );

    fdui->insert_input_title = obj = fl_add_input( FL_NORMAL_INPUT, 120, 200, 220, 30, "Title" );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );

    fdui->insert_input_artist = obj = fl_add_input( FL_NORMAL_INPUT, 120, 250, 220, 30, "Artist" );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );

    fdui->insert_input_borrower = obj = fl_add_input( FL_NORMAL_INPUT, 120, 300, 220, 30, "Borrower" );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );

    fdui->insert_button = obj = fl_add_button( FL_NORMAL_BUTTON, 120, 350, 130, 30, "Insert" );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );
    fl_set_object_callback( obj, insertRecordCallback, 0 );

    fl_end_group( );

    fdui->show_view = fl_bgn_group( );

    obj = fl_add_text( FL_NORMAL_TEXT, 70, 400, 230, 30, "Show" );
    fl_set_object_lsize( obj, FL_LARGE_SIZE );

    obj = fl_add_input( FL_NORMAL_INPUT, 140, 480, 220, 30, "Titel" );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );

    obj = fl_add_input( FL_NORMAL_INPUT, 420, 480, 220, 30, "Artist" );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );

    obj = fl_add_input( FL_NORMAL_INPUT, 740, 480, 220, 30, "Borrower" );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );

    obj = fl_add_text( FL_NORMAL_TEXT, 90, 440, 130, 30, "Search" );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );

    obj = fl_add_frame( FL_ENGRAVED_FRAME, 100, 550, 860, 560, "" );

    obj = fl_add_text( FL_NORMAL_TEXT, 110, 570, 140, 20, "text" );

    fl_end_group( );

    fdui->search_button = obj = fl_add_button( FL_NORMAL_BUTTON, 1010, 480, 130, 30, "Search" );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );
    fl_set_object_callback( obj, searchRecordsCallback, 0 );

    fl_end_form( );

    fdui->libformsGUI->fdui = fdui;

    return fdui;
}

// Callbacks
void insertRecordCallback( FL_OBJECT* source, long arg) {
    insertRecord();
}
void searchRecordsCallback( FL_OBJECT* source, long arg) {
    return;
}
